import Afro from './Images/Hairstyle/Afro.png'
import BuzzCut from './Images/Hairstyle/BuzzCut.png'
import CombOver from './Images/Hairstyle/CombOver.png'
import CornrowBraids from './Images/Hairstyle/CornrowBraids.png'
import CurlyShage from './Images/Hairstyle/CurlyShag.png'
import FauxHawk from './Images/Hairstyle/FauxHawk.png'
import HighTightFade from './Images/Hairstyle/HighTightFade.png'
import LongWavyCurtainBangs from './Images/Hairstyle/LongWavyCurtainBangs.png'
import LowFade from './Images/Hairstyle/LowFade.png'
import ManBun from './Images/Hairstyle/ManBun.png'
import MessyTousled from './Images/Hairstyle/MessyTousled.png'
import Middleparted from './Images/Hairstyle/Middleparted.png'
import Pompadour from './Images/Hairstyle/Pompadour.png'
import Spiky from './Images/Hairstyle/Spiky.png'
import TexturedFringe from './Images/Hairstyle/TexturedFringe.png'
import WavyShag from './Images/Hairstyle/WavyShag.png'
import SlickBack from './Images/Hairstyle/SlickBack.png'
import SidePartCombOverHairstyleWithHighFade from './Images/Hairstyle/SidePartCombOverHairstyleWithHighFade.png'

import CurlyBob from './Images/Hairstyle/CurlyBob.png'
import DoubleBun from './Images/Hairstyle/DoubleBun.png'
import FishtailBraid from './Images/Hairstyle/FishtailBraid.png'
import LongCurly from './Images/Hairstyle/LongCurly.png'
import LongStraight from './Images/Hairstyle/LongStraight.png'
import ShortCurlyPixie from './Images/Hairstyle/ShortCurlyPixie.png'
import ShortNeatBob from './Images/Hairstyle/ShortNeatBob.png'
import ShoulderLengthHair from './Images/Hairstyle/ShoulderLengthHair.png'
import Updo from './Images/Hairstyle/Updo.png'
import BoxBraids from './Images/Hairstyle/BoxBraids.png'


export const ChoiceList = [
    {
        id:11,
        hairstyle: 'HighTightFade',
        faceShape: 'oval',
        resource_type: 1,
        strength: 0.4,
        category: "Professional",
        gender: 'male',
        image: HighTightFade,
    },
    {
        id:12,
        hairstyle: 'WavyShag',
        faceShape: 'oval',
        resource_type: 0,
        strength: 0.4,
        category: "Casual",
        gender: 'male',
        image: WavyShag,
    },
    {
        id:13,
        hairstyle: 'FauxHawk',
        faceShape: 'oval',
        resource_type: 4,
        strength: 0.4,
        category: "Events",
        gender: 'male',
        image: FauxHawk,
    },
    {
        id:14,
        hairstyle: 'Afro',
        faceShape: 'oval',
        resource_type: 3,
        strength: 0.4,
        category: "Funky",
        gender: 'male',
        image: Afro,
    },
    {
        id:21,
        hairstyle: 'LowFade',
        faceShape: 'round',
        resource_type: 1,
        strength: 0.4,
        category: "Professional",
        gender: 'male',
        image: LowFade,
    },
    {
        id:22,
        hairstyle: 'MessyTousled',
        faceShape: 'round',
        resource_type: 0,
        strength: 0.4,
        category: "Casual",
        gender: 'male',
        image: MessyTousled,
    },
    {
        id:23,
        hairstyle: 'TexturedFringe',
        faceShape: 'round',
        resource_type: 4,
        strength: 0.4,
        category: "Events",
        gender: 'male',
        image: TexturedFringe,
    },
    {
        id:24,
        hairstyle: 'ManBun"',
        faceShape: 'round',
        resource_type: 3,
        strength: 0.4,
        category: "Funky",
        gender: 'male',
        image: ManBun,
    },
    {
        id:31,
        hairstyle: 'BuzzCut',
        faceShape: 'square',
        resource_type: 1,
        strength: 0.4,
        category: "Professional",
        gender: 'male',
        image: BuzzCut,
    },
    {
        id:32,
        hairstyle: 'Middle-parted',
        faceShape: 'square',
        resource_type: 0,
        strength: 0.4,
        category: "Casual",
        gender: 'male',
        image: Middleparted,
    },
    {
        id:33,
        hairstyle: 'SlickBack',
        faceShape: 'square',
        resource_type: 4,
        strength: 0.4,
        category: "Events",
        gender: 'male',
        image: SlickBack,
    },
    {
        id:34,
        hairstyle: 'LongWavyCurtainBangs',
        faceShape: 'square',
        resource_type: 3,
        strength: 0.4,
        category: "Funky",
        gender: 'male',
        image: LongWavyCurtainBangs,
    },
    {
        id:41,
        hairstyle: 'CombOver',
        faceShape: 'heart',
        resource_type: 1,
        strength: 0.4,
        category: "Professional",
        gender: 'male',
        image: CombOver,
    },
    {
        id:42,
        hairstyle: 'TexturedFringe',
        faceShape: 'heart',
        resource_type: 0,
        strength: 0.4,
        category: "Casual",
        gender: 'male',
        image: TexturedFringe,
    },
    {
        id:43,
        hairstyle: 'FauxHawk',
        faceShape: 'heart',
        resource_type: 4,
        strength: 0.4,
        category: "Events",
        gender: 'male',
        image: FauxHawk,
    },
    {
        id:44,
        hairstyle: 'CornrowBraids',
        faceShape: 'heart',
        resource_type: 3,
        strength: 0.4,
        category: "Funky",
        gender: 'male',
        image: CornrowBraids,
    },
    {
        id:51,
        hairstyle: 'SlickBack',
        faceShape: 'diamond',
        resource_type: 1,
        strength: 0.4,
        category: "Professional",
        gender: 'male',
        image: SlickBack,
    },
    {
        id:52,
        hairstyle: 'CurlyShag',
        faceShape: 'diamond',
        resource_type: 0,
        strength: 0.4,
        category: "Casual",
        gender: 'male',
        image: CurlyShage,
    },
    {
        id:53,
        hairstyle: 'Pompadour',
        faceShape: 'diamond',
        resource_type: 4,
        strength: 0.4,
        category: "Events",
        gender: 'male',
        image: Pompadour,
    },
    {
        id:54,
        hairstyle: 'Spiky',
        faceShape: 'diamond',
        resource_type: 3,
        strength: 0.4,
        category: "Funky",
        gender: 'male',
        image: Spiky,
    },
    {
        id:111,
        hairstyle: 'SidePartCombOverHairstyleWithHighFade',
        faceShape: 'oval',
        resource_type: 4,
        strength: 0.7,
        category: "Professional",
        gender: 'female',
        image: SidePartCombOverHairstyleWithHighFade,
    },
    {
        id:122,
        hairstyle: 'LongStraight',
        faceShape: 'oval',
        resource_type: 2,
        strength: 0.7,
        category: "Casual",
        gender: 'female',
        image: LongStraight,
    },
    {
        id:133,
        hairstyle: 'FishtailBraid',
        faceShape: 'oval',
        resource_type: 6,
        strength: 0.9,
        category: "Events",
        gender: 'female',
        image: FishtailBraid,
    },
    {
        id:144,
        hairstyle: 'ShortCurlyPixie',
        faceShape: 'oval',
        resource_type: 5,
        strength: 0.7,
        category: "Funky",
        gender: 'female',
        image: ShortCurlyPixie,
    },
    {
        id:211,
        hairstyle: 'ShortNeatBob',
        faceShape: 'round',
        resource_type: 4,
        strength: 0.7,
        category: "Professional",
        gender: 'female',
        image: ShortNeatBob,
    },
    {
        id:222,
        hairstyle: 'FishtailBraid',
        faceShape: 'round',
        resource_type: 2,
        strength: 0.7,
        category: "Casual",
        gender: 'female',
        image: FishtailBraid,
    },
    {
        id:233,
        hairstyle: 'ShoulderLengthHair',
        faceShape: 'round',
        resource_type: 6,
        strength: 0.9,
        category: "Events",
        gender: 'female',
        image: ShoulderLengthHair,
    },
    {
        id:244,
        hairstyle: 'BoxBraids',
        faceShape: 'round',
        resource_type: 5,
        strength: 0.7,
        category: "Funky",
        gender: 'female',
        image: BoxBraids,
    },
    {
        id:311,
        hairstyle: 'SlickedBack',
        faceShape: 'square',
        resource_type: 4,
        strength: 0.7,
        category: "Professional",
        gender: 'female',
        image: SlickBack,
    },
    {
        id:322,
        hairstyle: 'CurlyBob',
        faceShape: 'square',
        resource_type: 2,
        strength: 0.7,
        category: "Casual",
        gender: 'female',
        image: CurlyBob,
    },
    {
        id:333,
        hairstyle: 'FishtailBraid',
        faceShape: 'square',
        resource_type: 6,
        strength: 0.9,
        category: "Events",
        gender: 'female',
        image: FishtailBraid,
    },
    {
        id:344,
        hairstyle: 'DoubleBun',
        faceShape: 'square',
        resource_type: 5,
        strength: 0.7,
        category: "Funky",
        gender: 'female',
        image: DoubleBun,
    },
    {
        id:411,
        hairstyle: 'SidePartCombOverHairstyleWithHighFade',
        faceShape: 'heart',
        resource_type: 4,
        strength: 0.7,
        category: "Professional",
        gender: 'female',
        image: SidePartCombOverHairstyleWithHighFade,
    },
    {
        id:422,
        hairstyle: 'DoubleBun',
        faceShape: 'heart',
        resource_type: 2,
        strength: 0.7,
        category: "Casual",
        gender: 'female',
        image: DoubleBun,
    },
    {
        id:433,
        hairstyle: 'ShoulderLengthHair',
        faceShape: 'heart',
        resource_type: 6,
        strength: 0.9,
        category: "Events",
        gender: 'female',
        image: ShoulderLengthHair,
    },
    {
        id:444,
        hairstyle: 'CurlyBob',
        faceShape: 'heart',
        resource_type: 5,
        strength: 0.7,
        category: "Funky",
        gender: 'female',
        image: CurlyBob,
    },
    {
        id:511,
        hairstyle: 'ShortNeatBob',
        faceShape: 'diamond',
        resource_type: 4,
        strength: 0.7,
        category: "Professional",
        gender: 'female',
        image: ShortNeatBob,
    },
    {
        id:522,
        hairstyle: 'LongCurly',
        faceShape: 'diamond',
        resource_type: 2,
        strength: 0.7,
        category: "Casual",
        gender: 'female',
        image: LongCurly,
    },
    {
        id:533,
        hairstyle: 'Updo',
        faceShape: 'diamond',
        resource_type: 6,
        strength: 0.9,
        category: "Events",
        gender: 'female',
        image: Updo,
    },
    {
        id:544,
        hairstyle: 'LongCurly',
        faceShape: 'diamond',
        resource_type: 5,
        strength: 0.7,
        category: "Funky",
        gender: 'female',
        image: LongCurly,
    },
]