export const HairColor = [
    {
        id:'blonde',
        color:'#fbe7a1',
    },
    {
        id:'platinumBlonde',
        color:'#D0D1CB',
    },
    {
        id:'brown',
        color:'#964B00',
    },
    {
        id:'lightBrown',
        color:'#C4A484',
    },
    {
        id:'blue',
        color:'#0000FF',
    },
    {
        id:'lightBlue',
        color:'#ADD8E6'
    },
    {
        id:'purple',
        color:'#800080',
    },
    {
        id:'lightPurple',
        color:'#CBC3E3',
    },
    {
        id:'pink',
        color:'#FFC0CB',
    },
    {
        id:'black',
        color:'#000000',
    },
    {
        id:'white',
        color:'#FFFFFF',
    },
    {
        id:'grey',
        color:'#808080',
    },
    {
        id:'silver',
        color:'#C0C0C0',
    },
    {
        id:'red',
        color:'#FF0000',
    },
    {
        id:'orange',
        color:'#FFA500',
    },
    {
        id:'green',
        color:'	#008000',
    },
    {
        id:'gradient',
        color:'#33ccff',
    },
    {
        id:'multicolored',
        color:'	#008284',
    },
    {
        id:'darkBlue',
        color:'#00008b',
    },
    {
        id:'burgundy',
        color:'#8C001A',
    },
    {
        id:'darkGreen',
        color:'#006400',
    },
]
