# Generated by Django 5.0.3 on 2024-03-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LipColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=100)),
                ('OrginalImage', models.FileField(blank=True, null=True, upload_to='LipColor/OriginalImage/')),
                ('FilteredImage', models.FileField(blank=True, null=True, upload_to='LipColor/FilteredImage/')),
                ('WishList', models.BooleanField(default=False)),
            ],
        ),
    ]
