# Generated by Django 5.0.3 on 2024-03-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyebrow', '0002_eyebrowtmp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EyebrowTMP',
        ),
    ]
