# Generated by Django 5.0.3 on 2024-03-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HairStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UserName", models.CharField(max_length=100, unique=True)),
                (
                    "OrginalImage",
                    models.FileField(
                        blank=True, null=True, upload_to="HairStyle/OriginalImage/"
                    ),
                ),
                (
                    "FilteredImage",
                    models.FileField(
                        blank=True, null=True, upload_to="HairStyle/FilteredImage/"
                    ),
                ),
                ("WishList", models.BooleanField(default=False)),
            ],
        ),
    ]
