# Generated by Django 5.0.3 on 2024-03-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hairstyle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hairstyle",
            name="FilteredImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="HairStyle/FilteredImage/"
            ),
        ),
        migrations.AlterField(
            model_name="hairstyle",
            name="OrginalImage",
            field=models.ImageField(
                blank=True, null=True, upload_to="HairStyle/OriginalImage/"
            ),
        ),
        migrations.AlterField(
            model_name="hairstyle",
            name="UserName",
            field=models.CharField(max_length=100),
        ),
    ]
